import "bootstrap/dist/css/bootstrap.min.css";
import React from "react";
import { Link } from "react-router-dom";

export default function AboutUs() {
  return (
    <div className="container mt-5">
      {/* Title Section */}
      <h1 className="text-center fw-bold mb-4">About AutoDocX</h1>
      
      {/* Description Section */}
      <p className="lead text-center text-muted">
        AutoDocX is a cutting-edge **Software Documentation Tool** that leverages advanced code analysis 
        and **Large Language Models (LLMs)** to automatically generate high-quality documentation for your 
        GitHub repositories. It takes the complexity out of understanding and documenting codebases, making it easier 
        to share, maintain, and collaborate on projects.
      </p>

      {/* Features Section */}
      <div className="mt-5">
        <h3 className="fw-bold">🔹 Key Features</h3>
        <ul className="list-group list-group-flush">
          <li className="list-group-item">📌 **Automated Documentation Generation** – Uses LLMs and code analysis to create well-structured documentation from your GitHub repositories.</li>
          <li className="list-group-item">📌 **Code Commenting with AI** – Automatically adds meaningful comments to your code, improving its readability.</li>
          <li className="list-group-item">📌 **Comprehensive Documentation Output** – Generates detailed API documentation, class descriptions, and module overviews.</li>
          <li className="list-group-item">📌 **Seamless GitHub Integration** – Directly integrates with GitHub to fetch your repository and analyze the code.</li>
          <li className="list-group-item">📌 **Customizable Documentation Formats** – Choose from Markdown, HTML, or PDF formats to suit your needs.</li>
          <li className="list-group-item">📌 **Multilingual Support** – Supports JavaScript, Python, C++, and other major programming languages.</li>
        </ul>
      </div>

      {/* Technology Stack */}
      <div className="mt-5">
        <h3 className="fw-bold">🛠️ Technology Stack</h3>
        <p>
          AutoDocX utilizes a modern technology stack to provide powerful and efficient documentation generation:
        </p>
        <ul>
          <li>🌍 **Frontend**: React.js, Bootstrap for responsive design</li>
          <li>⚙️ **Backend**: Node.js, Express.js for scalable server-side processing</li>
          <li>📄 **Database**: MongoDB for storing user data and configuration</li>
          <li>🔍 **AI/ML**: Leveraging NLP (Natural Language Processing) and LLMs for intelligent code analysis and documentation generation</li>
          <li>📡 **APIs**: GitHub API to fetch and analyze repositories</li>
        </ul>
      </div>

      {/* Why Choose AutoDocX? */}
      <div className="mt-5">
        <h3 className="fw-bold">🚀 Why Choose AutoDocX?</h3>
        <p>
          Writing documentation can be time-consuming and tedious, especially for large projects. AutoDocX helps solve this by automating the documentation process using advanced code analysis and LLMs, giving you more time to focus on development. 
        </p>
        <ul>
          <li>⚡ **Automates Documentation** – No need to manually write documentation for your code.</li>
          <li>💡 **Improves Code Understanding** – Makes your codebase easy to understand for both new and existing team members.</li>
          <li>📚 **Enhances Collaboration** – Well-documented code fosters better collaboration and communication among developers.</li>
          <li>🔍 **Powerful AI Insights** – Intelligent comments and documentation generated by LLMs improve code clarity.</li>
          <li>🛠 **Open-Source Friendly** – Great for open-source projects that require consistent and clear documentation.</li>
        </ul>
      </div>

      {/* Call to Action */}
      <div className="text-center mt-5">
        <h3>Ready to Automate Your Documentation?</h3>
        <p>Try AutoDocX today and generate high-quality documentation with ease!</p>
        <Link to="/get-started">
          <a href="#" className="btn btn-primary btn-lg">Get Started</a>
        </Link>
      </div>
    </div>
  );
}
